HIHIGH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns=[
    path('', views.index, name='index'),
    path('<int:movie_id>/like/', views.movies_like, name='movies_like'),

    path('review_board/', views.review_board, name='review_board'), #리뷰게시판
    path('review_board/create/', views.review_create, name='review_create'),
    path('review_board/<int:movie_id>/<int:review_id>/', views.review_detail, name='review_detail'),
    path('review_board/<int:movie_id>/<int:review_id>/update/', views.review_update, name='review_update'),
    path('review_board/<int:movie_id>/<int:review_id>/delete/', views.review_delete, name='review_delete'),

    path('comment/<int:movie_id>/<int:review_id>/create/', views.comment_create, name='comment_create'),
    path('comment/<int:movie_id>/<int:review_id>/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('comment/<int:movie_id>/<int:review_id>/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    path('recommend/<str:name>', views.recommend, name='recommend'),
    path('recommend2/<str:name>', views.recommend2, name='recommend2'),

    path('qna_board/', views.qna_board, name='qna_board'),
    path('qna_board/create/', views.qna_create, name='qna_create'),
    path('qna_board/<int:qna_id>', views.qna_detail, name='qna_detail'),
    path('qna_board/<int:qna_id>/update', views.qna_update, name='qna_update'),
    path('qna_board/<int:qna_id>/delete', views.qna_delete, name='qna_delete'),

    path('qnacomment/<int:qna_id>/create/', views.qnacomment_create, name='qnacomment_create'),
    path('qnacomment/<int:qna_id>/<int:qnacomment_id>/update/', views.qnacomment_update, name='qnacomment_update'),
    path('qnacomment/<int:qna_id>/<int:qnacomment_id>/delete/', views.qnacomment_delete, name='qnacomment_delete'),

]

movies/models.py
from django.db import models
from django.conf import settings
import json
import requests
from decouple import config

class Movie(models.Model):
    movie_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    director = models.CharField(max_length=100)
    overview = models.TextField()
    release_date = models.CharField(max_length=50)
    poster_path = models.CharField(max_length=150)
    backdrop_path = models.CharField(max_length=150)
    movie_num = models.CharField(max_length=50)
    rate = models.DecimalField(max_digits=3, decimal_places=2)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)
    

    def __str__(self):
        return self.movie_title

    @classmethod
    def get_movie_data(mov, first_page, last_page):
        API_TMD_KEY = config('API_TMD_KEY')
        for num in range(first_page, last_page):

            page_num = str(num)
            MOVIE_LIST_URL = f"https://api.themoviedb.org/3/discover/movie?api_key={API_TMD_KEY}&language=ko-KR&page={page_num}"
            movie_list_data = requests.get(MOVIE_LIST_URL)
            result_data = movie_list_data.json().get('results')

            for res in result_data:
                movie_num = res.get('id')
                movie_title = res.get('title')
                if res.get('poster_path'):
                    poster_path = "https://image.tmdb.org/t/p/original"+ res.get('poster_path')
                else:
                    poster_path = ""
                if res.get('backdrop_path'):
                    backdrop_path = "https://image.tmdb.org/t/p/original"+ res.get('backdrop_path')
                else:
                    backdrop_path = ""
                rate = res.get('vote_average')
                
                MOVIE_DETAIL_URL = f"https://api.themoviedb.org/3/movie/{movie_num}?api_key={API_TMD_KEY}&language=ko-KR"
                movie_detail_data = requests.get(MOVIE_DETAIL_URL)

                if movie_detail_data.json().get('genres'):
                    genre = movie_detail_data.json().get('genres')[0].get('name')
                else:
                    genre = ""

                overview = str(movie_detail_data.json().get('overview'))
                release_date = str(movie_detail_data.json().get('release_date'))

                MOVIE_CREDITS_URL = f"https://api.themoviedb.org/3/movie/{movie_num}/credits?api_key={API_TMD_KEY}"
                credits_data = requests.get(MOVIE_CREDITS_URL)
                directors_data = credits_data.json().get('crew')
                
                for i in range(len(directors_data)):
                    if directors_data[i].get('job') =='Director':
                        director = directors_data[i].get('name')
                        break
                    else:
                        director = ""

                mov.objects.get_or_create(
                    movie_title=movie_title,
                    genre=genre,
                    director=director,
                    overview=overview,
                    release_date=release_date,
                    poster_path= poster_path,
                    backdrop_path=backdrop_path,
                    movie_num=movie_num,
                    rate = rate,
                )



class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class Qna(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Qnacomment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    qna = models.ForeignKey(Qna, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from .models import Movie, Review, Comment, Qna, Qnacomment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    PICKS = [
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]

    rank = forms.ChoiceField(choices=PICKS, widget=forms.Select())

    class Meta:
        model = Review
        fields = ['movie', 'title', 'rank', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class QnaForm(forms.ModelForm):
    class Meta:
        model = Qna
        fields = ['title','content']

class QnacommentForm(forms.ModelForm):
    class Meta:
        model = Qnacomment
        fields = ['content']

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review, Comment, Qna, Qnacomment
from .forms import MovieForm, ReviewForm, CommentForm, QnaForm, QnacommentForm
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q
from collections import Counter

# Create your views here.

def index(request):       
    movie_li = Movie.objects.order_by('-id')
    reviews = Review.objects.all()

    review_form = ReviewForm()

    paginator = Paginator(movie_li, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context={
        'movie_li':movie_li,
        'reviews':reviews,
        'page_obj':page_obj,
        'review_form': review_form,
    }

    return render(request, 'movies/index.html', context)

def review_board(request):
    reviews=Review.objects.all()
    review_form = ReviewForm()
    context={
        'reviews':reviews,
        'review_form': review_form,
    }
    return render(request, 'movies/review_board.html', context)

def review_create(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('movies:review_detail', review.movie.id, review.id)
    else:
        form = ReviewForm()
    context = {
        'form': form
    }
    return render(request, 'movies/review_form.html', context)

def review_detail(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    
    review_form = ReviewForm(instance=review)
    comment_form = CommentForm()
    context = {
        'movie':movie,
        'review': review,
        'review_form': review_form,
        'comment_form': comment_form,
    }
    return render(request, 'movies/review_detail.html', context)

def review_update(request, movie_id, review_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)

    if request.user == review.user:
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, instance=review)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.user = request.user
                review.save()
                return redirect('movies:review_detail', movie.id, review.id)
        else:
            review_form = ReviewForm(instance=review)
        context = {
            'reivew_form': review_form,
        }
        return render(request, 'movies/review_form.html', context)
    else:
        return redirect('movies:index')

def review_delete(request, movie_id, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user == review.user:
        review.delete()
    return redirect('movies:review_board')

def comment_create(request, movie_id, review_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.review = review
        comment.save()
    return redirect('movies:review_detail', movie.id, review.id)

def comment_update(request, movie_id, review_id, comment_id):
    movie = get_object_or_404(Movie, id=movie_id)
    review = get_object_or_404(Review, id=review_id)
    comment = get_object_or_404(Comment, id=comment_id)

    if request.user == comment.user:
        if request.method == 'POST':
            comment_form = CommentForm(request.POST, instance=comment)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.user = comment.user
                comment.save()
                return redirect('movies:review_detail', movie.id, review.id)
        else:
            comment_form = CommentForm(instance=comment)
        context = {
            'comment_form': comment_form,
        }

        return render(request, 'movies/comment_form.html', context)
    else:
        return redirect('movies:index')

def comment_delete(request, movie_id, review_id, comment_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    if request.method == 'POST':
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user == comment.user:
            comment.delete()
    return redirect('movies:review_detail', movie_id, review_id)


def movies_like(request, movie_id):
    user = request.user
    movie = get_object_or_404(Movie, id=movie_id)

    if movie.like_users.filter(id=user.id).exists():
        movie.like_users.remove(user)
        liked = False
    else:
        movie.like_users.add(user)
        liked = True

    context = {
        "liked" : liked,
        "count" : movie.like_users.count(),
    }

    return JsonResponse(context)

@login_required
def recommend(request, name):

    current_user = get_object_or_404(get_user_model(), username=name)

    directors = current_user.like_movies.exclude(Q(director__isnull=True) | Q(director=''))

    director_list = []

    like_movie_list = []

    director_names = []
    
    directors_movies = []

    for d in directors:
        director_list.append(d.director)
        like_movie_list.append(d.movie_title)

    director_most = Counter(director_list).most_common()

    for d in director_most:
        director_names.append(d[0])

    for d in director_names:
        movie_li = Movie.objects.filter(director=d).order_by('-rate')
        if len(movie_li) > 1:
            directors_movies.append(movie_li)

    context={
        'directors_movies' : directors_movies,
        'like_movie_list' : like_movie_list,
    }

    return render(request, 'movies/recommend.html', context)


#내가 좋아요한 영화 장르의 평점 순으로 30개 영화 추천하기
@login_required
def recommend2(request, name):
    person = get_object_or_404(get_user_model(), username=name) #유저
    like_movies=person.like_movies.all() # 내가 좋아요 누른 영화들
    movie_all = Movie.objects.all() # 평점으로 영화 줄세우기 
    reviews=Review.objects.all()
    
    genres={} #모든 장르
    

    if len(like_movies)>0: #좋아요 누른 영화가 1개 이상일 때
        
        for g in movie_all: #장르 개수를 세기위한 dictionary 만들기
            genres[g.genre]=0

        for movie in like_movies: #좋아요 누른 영화를 하나씩 뽑아서 뽑은 영화의 장르들을 dictionary에 넣기
            genres[movie.genre] += 1
        
        def f(x):
            return x[1]

        result=genres.items()

        genre=[] 
        
        for key, value in result:
            if value!=0:
                genre.append(key) #내가 좋아하는 장르만

        rates={}

        for movie in movie_all: # 모든 영화에서
            if movie.genre in genre:
                #좋아하는 장르가 있는 영화 제목과 평점을 불러오기
                rates[movie.movie_title]=float(movie.rate)
        
        res = sorted(rates.items(), key=f, reverse=True)  # 평점 내리차순으로 정렬

        recommend = []

        for movie in movie_all:
            for i in range(30):
                if movie.movie_title==res[i][0]:
                    recommend.append(movie)


    else:
        recommend=[]

    paginator = Paginator(recommend,6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
        

    context={
        'recommend':recommend,
        'reviews':reviews,
        'page_obj':page_obj,
    }

    return render(request, 'movies/recommend2.html', context)

@login_required
def qna_board(request):
    qnas=Qna.objects.all()
    qna_form = QnaForm()
    context={
        'qnas':qnas,
        'qna_form': qna_form,
    }
    return render(request, 'movies/qna_board.html', context)


@login_required
def qna_create(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    if request.method == 'POST':
        form = QnaForm(request.POST)
        if form.is_valid():
            qna = form.save(commit=False)
            qna.user = request.user
            qna.save()
            return redirect('movies:qna_detail', qna.id)
    else:
        form = QnaForm()
    context = {
        'form': form
    }
    return render(request, 'movies/qna_form.html', context)

def qna_detail(request, qna_id):
    qna = get_object_or_404(Qna, id=qna_id)
    qna_form = QnaForm(instance=qna)
    qnacomment_form = QnacommentForm()
    context = {
        'qna':qna,
        'qna_form': qna_form,
        'qnacomment_form':qnacomment_form,
    }
    return render(request, 'movies/qna_detail.html', context)

def qna_update(request,qna_id):
    qna = get_object_or_404(Qna, id=qna_id)

    if request.user == qna.user:
        if request.method == 'POST':
            qna_form = QnaForm(request.POST, instance=qna)
            if qna_form.is_valid():
                qna = qna_form.save(commit=False)
                qna.user = request.user
                qna.save()
                return redirect('movies:qna_detail', qna.id)
        else:
            qna_form = QnaForm(instance=qna)
        context = {
            'qna_form': qna_form,
        }
        return render(request, 'movies/qna_form.html', context)
    else:
        return redirect('movies:index')

def qna_delete(request, qna_id):
    qna = get_object_or_404(Qna, id=qna_id)
    if request.user == qna.user:
        qna.delete()
    return redirect('movies:qna_board')

def qnacomment_create(request, qna_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    qna = get_object_or_404(Qna, id=qna_id)

movies/templates/movies/comment_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<style>
  h3 {
    color: #70c7be;
    font-weight: bold;
  }

  label {
    color: whitesmoke;
  }

  .form-text {
    color: beige;
  }

  .form-control {
    background-color: rgb(34, 34, 34);
    border-color: #9d7ed0;
    color: white;

  }
</style>

<div class="container mt-5">
  <h2 class="text-white" style="font-family: 'Do Hyeon', sans-serif;">수정하기</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="btn" style="color:white;font-family: 'Do Hyeon', sans-serif; background-color:#9d7ed0;">submit</button>
  </form>
</div>
<br>
{% endblock %}

movies/templates/movies/qna_detail.html
<link rel="shortcut icon" href="../../../../../static/favicon.ico" type="image/x-icon">
<link rel="icon" href="../../../../../static/favicon.ico" type="image/x-icon">

{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<style>
	.modal-content {
	background-color: rgb(34,34,34);
	color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  select#id_movie.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  input#id_title.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  select#id_rank.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  textarea#id_content.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
</style>
<div class="d-flex justify-content-center">
	<div class="d-inline" style="width:33%;">
		<div class="card" style="width: 42rem; background-color: transparent; color:white">
			<div class="card-body" style="font-family: 'Do Hyeon', sans-serif;">
				<h2 class="card-title">{{ qna.title }}</h2>
                <p class="card-text">{{ qna.content }}</p>
                <p class="card-text">{{ qna.user }}</p>
				<p>Last created: {{ qna.created_at }}</p>
				<p>Last updated: {{ qna.updated_at }}</p>
				{% if user == qna.user %}
				<div class="d-inline">
					<button type="button" class="btn d-inline" data-toggle="modal" data-target="#exampleModal_1" style="background-color:#9d7ed0; color:white">
						수정하기
					</button>
					<form class="d-inline" action="{% url 'movies:qna_delete' qna.id %}" method="POST">
						{% csrf_token %}
						<button role="button" class="btn" style="background-color: #7f92cf; color:white">삭제하기</button>
					</form>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="exampleModal_1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel" style="color:#7e4bcf;">리뷰</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true" style="color:white;"><i class="fas fa-times"></i></span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{% url 'movies:qna_update' qna.id %}" method="POST" class="form">
					{% csrf_token %}
					{% bootstrap_form qna_form layout="inline" %}
					<button type="submit" class="btn" style="background-color:#70c7be; color:white;">submit</button>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn" data-dismiss="modal" style="background-color:#7f92cf; color:white;">Close</button>
			</div>
		</div>
	</div>
</div>

<div class="container mt-5">
	<h3 style="color:white; text-align:center; font-family:'Acme', sans-serif;"><i class="fas fa-comments"></i>&nbsp;Q&A_COMMENTS</h3>
	<table class="table table-dark mt-4">
		<thead>
			<tr style="background-color: #70c7be; font-family: 'Do Hyeon', sans-serif; font-size:large;">
				<th scope="col" style="text-align:center;">번호</th>
				<th scope="col" style="text-align:center;">댓글</th>
				<th scope="col" style="text-align:center;">작성자</th>
				<th scope="col" style="text-align:center;">Edit</th>
				<th scope="col" style="text-align:center;">Delete</th>
			</tr>
		</thead>
		<tbody>
		{% for qnacomment in qna.qnacomment_set.all %}
			<tr style="background-color:rgb(34,34,34); color:white; text-align: center; font-family: 'Do Hyeon', sans-serif; font-size:large;">
				<th scope="row">{{ forloop.counter }}</th>
				<td>{{ qnacomment.content }}</td>
				<td>{{ qnacomment.user }}</td>
				<td>
					{% if qnacomment.user == user %}
					<a href="{% url 'movies:qnacomment_update' qna.id qnacomment.id %}"><button type="button" class="btn btn-outline-secondary btn-sm" style="background-color:#9d7ed0; color:white">수정</button></a>
					{% endif %}
				</td>
				<td>
					{% if qnacomment.user == user %}
					<form action="{% url 'movies:qnacomment_delete' qna.id qnacomment.id %}" method = "POST">
						{% csrf_token %}
							<button class="btn btn-outline-secondary btn-sm" style="background-color:#7f92cf; color:white">삭제</button>
					</form>
					{% endif %}
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
	<br>
	{% if request.user.is_staff %}
		<form action="{% url 'movies:qnacomment_create' qna.id %}" method="POST">
		{% csrf_token %}
		{% bootstrap_form qnacomment_form layout="inline" %}
		<button class="btn" style="background-color: orange; color:white; font-family:'Acme', sans-serif;">ADD COMMENT</button>
		</form>
	{% endif %}
</div>
<br>


{% endblock %}

movies/templates/movies/review_detail.html
<link rel="shortcut icon" href="../../../../../static/favicon.ico" type="image/x-icon">
<link rel="icon" href="../../../../../static/favicon.ico" type="image/x-icon">

{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<style>
	.modal-content {
	background-color: rgb(34,34,34);
	color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  select#id_movie.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  input#id_title.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  select#id_rank.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
  textarea#id_content.form-control{
    background-color: rgb(34,34,34);
    color:white;
	font-family: 'Do Hyeon', sans-serif;
  }
</style>
<div class="d-flex justify-content-center">
	<div class="d-inline mr-1" style="width:33%;">
		{% if movie.backdrop_path|length != 0 %}
			<img src="{{ movie.backdrop_path }}" style="width:100%; height:100%; opacity:0.7;" alt="">
		{% else %}
			<img src="../../../static/no_image2.JPG" style="width:100%; height:50%; opacity:0.7;" alt="">
		{% endif %}
	</div>


	<div class="d-inline" style="width:33%;">
		<div class="card" style="width: 42rem; background-color: transparent; color:white">
			<div class="card-body" style="font-family: 'Do Hyeon', sans-serif;">
				<h2 class="card-title">{{ movie.movie_title }}</h2>
				<h3 class="card-text">{{ review.title }}</h3>
				<p class="card-text">평점 : {{ review.rank }}점</p>
				<p class="card-text">{{ review.content }}</p>
				<p>Last created: {{ review.created_at }}</p>
				<p>Last updated: {{ review.updated_at }}</p>
				{% if user == review.user %}
				<div class="d-inline">
					<button type="button" class="btn d-inline" data-toggle="modal" data-target="#exampleModal_1" style="background-color:#9d7ed0; color:white">
						수정하기
					</button>
					<form class="d-inline" action="{% url 'movies:review_delete' movie.id review.id %}" method="POST">
						{% csrf_token %}
						<button role="button" class="btn" style="background-color: #7f92cf; color:white">삭제하기</button>
					</form>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="exampleModal_1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel" style="color:#7e4bcf;">리뷰</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true" style="color:white;"><i class="fas fa-times"></i></span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{% url 'movies:review_update' movie.id review.id %}" method="POST" class="form">
					{% csrf_token %}
					{% bootstrap_form review_form layout="inline" %}
					<button type="submit" class="btn" style="background-color:#70c7be; color:white;">submit</button>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn" data-dismiss="modal" style="background-color:#7f92cf; color:white;">Close</button>
			</div>
		</div>
	</div>
</div>

<br>

<div class="container mt-5">
	<h3 style="color:white; text-align:center; font-family:'Acme', sans-serif;"><i class="fas fa-comments"></i>&nbsp;COMMENTS</h3>
	<table class="table table-dark mt-4">
		<thead>
			<tr style="background-color: #70c7be; font-family: 'Do Hyeon', sans-serif; font-size:large;">
				<th scope="col" style="text-align:center;">번호</th>
				<th scope="col" style="text-align:center;">댓글</th>
				<th scope="col" style="text-align:center;">작성자</th>
				<th scope="col" style="text-align:center;">Edit</th>
				<th scope="col" style="text-align:center;">Delete</th>
			</tr>
		</thead>
		<tbody>
		{% for comment in review.comment_set.all %}
			<tr style="background-color:rgb(34,34,34); color:white; text-align: center; font-family: 'Do Hyeon', sans-serif; font-size:large;">
				<th scope="row">{{ forloop.counter }}</th>
				<td>{{ comment.content }}</td>
				<td>{{ comment.user }}</td>
				<td>
					{% if comment.user == user %}
					<a href="{% url 'movies:comment_update' movie.id review.id comment.id %}"><button type="button" class="btn btn-outline-secondary btn-sm" style="background-color:#9d7ed0; color:white">수정</button></a>
					{% endif %}
				</td>
				<td>
					{% if comment.user == user %}
					<form action="{% url 'movies:comment_delete' movie.id review.id comment.id %}" method = "POST">
						{% csrf_token %}
							<button class="btn btn-outline-secondary btn-sm" style="background-color:#7f92cf; color:white">삭제</button>
					</form>
					{% endif %}
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
	<br>
	{% if request.user.is_authenticated %}
		<form action="{% url 'movies:comment_create' movie.id review.id %}" method="POST">
		{% csrf_token %}
		{% bootstrap_form comment_form layout="inline" %}
		<button class="btn" style="background-color: orange; color:white; font-family:'Acme', sans-serif;">ADD COMMENT</button>
		</form>
	{% endif %}
</div>
{% endblock %}