HIHIGH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns=[
    path('', views.index, name='index'),
    path('<int:movie_id>/like/', views.movies_like, name='movies_like'),

    path('review_board/', views.review_board, name='review_board'), #리뷰게시판
    path('review_board/create/', views.review_create, name='review_create'),
    path('review_board/<int:movie_id>/<int:review_id>/', views.review_detail, name='review_detail'),
    path('review_board/<int:movie_id>/<int:review_id>/update/', views.review_update, name='review_update'),
    path('review_board/<int:movie_id>/<int:review_id>/delete/', views.review_delete, name='review_delete'),

    path('comment/<int:movie_id>/<int:review_id>/create/', views.comment_create, name='comment_create'),
    path('comment/<int:movie_id>/<int:review_id>/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('comment/<int:movie_id>/<int:review_id>/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

    path('recommend/<str:name>', views.recommend, name='recommend'),
    path('recommend2/<str:name>', views.recommend2, name='recommend2'),

    path('qna_board/', views.qna_board, name='qna_board'),
    path('qna_board/create/', views.qna_create, name='qna_create'),
    path('qna_board/<int:qna_id>', views.qna_detail, name='qna_detail'),
    path('qna_board/<int:qna_id>/update', views.qna_update, name='qna_update'),
    path('qna_board/<int:qna_id>/delete', views.qna_delete, name='qna_delete'),

    path('qnacomment/<int:qna_id>/create/', views.qnacomment_create, name='qnacomment_create'),
    path('qnacomment/<int:qna_id>/<int:qnacomment_id>/update/', views.qnacomment_update, name='qnacomment_update'),
    path('qnacomment/<int:qna_id>/<int:qnacomment_id>/delete/', views.qnacomment_delete, name='qnacomment_delete'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title id=>MOVIE_HIHIGH</title>
    
    <link rel="shortcut icon" href="../static/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../static/favicon.ico" type="image/x-icon">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/fb1b367961.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic+Coding&family=Sunflower:wght@300&family=Acme&family=Do+Hyeon&family=Josefin+Sans:ital,wght@1,600&family=Metal+Mania&family=Staatliches&display=swap" rel="stylesheet">
</head>
<body>
  <style>
    a:hover{
      text-decoration:none;
    }
    body{
      background-color:black;
    }
    .dropdown-menu {
      background-color:rgb(34,34,34);
    }
    .dropdown-item{
      color:white;
      text-align:center;
    }
    .dropdown-item:hover{
      background-color: #9d7ed0;
      color:white;
      text-align:center;
    }

    .wrapper {
      min-height: 100%;
      margin: 0 auto -60px;
    }


    footer, .push {
      height: 60px;
    }
    
  </style>
  <div class='wrapper'>
    <nav class="py-3 navbar navbar-expand-lg navbar-dark" style="background-color:rgb(34,34,34)">
      <a class="ml-3 navbar-brand font-weight-bold" style="font-size:xx-large; color:orangered" href="{% url 'movies:index' %}">
        <i class="fab fa-houzz" style="color:orangered"></i>&nbsp;HIHIGH</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item active" style="font-size:large;">
              <span class="mr-3 nav-link" style="color:gold; font-family: 'Staatliches', cursive; font-family: 'Do Hyeon', sans-serif; font-size:x-large">WELCOME~ <i class="far fa-laugh-squint"></i>&nbsp;{{ request.user.username }}</span>
            </li>
            <li class="nav-item active" style="font-size:large;">
              <a class="mr-3 nav-link" href="{% url 'movies:review_board' %}" style="color:#70c7be; font-family: 'Staatliches', cursive; font-size:x-large"><i class="fas fa-clipboard"></i>&nbsp;Review Board<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown active" style="font-size:large;">
              <a class="mr-3 nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" style="color:#7f92cf; font-family: 'Staatliches', cursive; font-size:x-large">
                <i class="far fa-list-alt"></i>&nbsp;Recommend<span class="sr-only">(current)</span></a>
              <div class="dropdown-menu">
                <a class="dropdown-item" style=" font-family: 'Do Hyeon', sans-serif; font-size:large;" href="{% url 'movies:recommend2' request.user.username %}">장르별</a>
                <a class="dropdown-item" style=" font-family: 'Do Hyeon', sans-serif; font-size:large;" href="{% url 'movies:recommend' request.user.username %}">감독별</a>
              </div>
            </li>
            <li class="nav-item active" style="font-size:large;">
              <a class="mr-3 nav-link" href="{% url 'movies:qna_board' %}" style="color:#9d7ed0; font-family: 'Staatliches', cursive; font-size:x-large"><i class="far fa-question-circle"></i>&nbsp;Q&A Board<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active" style="font-size:large;">
              <a class="mr-3 nav-link" href="{% url 'accounts:logout' %}" style="color:lightgrey; font-family: 'Staatliches', cursive; font-size:x-large">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="nav-item active" style="font-size:large;">
              <a class="mr-3 nav-link" href="{% url 'accounts:login' %}" style="color:#70c7be; font-family: 'Staatliches', cursive; font-size:x-large"><i class="fas fa-tape"></i>&nbsp;Login<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active" style="font-size:large;">
              <a class="mr-3 nav-link" href="{% url 'accounts:signup' %}" style="color:#7f92cf; font-family: 'Staatliches', cursive; font-size:x-large"><i class="fas fa-user-plus"></i>&nbsp;Sign up<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
          </ul>
      </div>
    </nav>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  
  {% block content %}
  {% endblock %}
  <div class="push"></div>
  </div>

  <footer id="footer" class="d-flex justify-content-center">
    <div class="inner">
      <ul class="icons" style="list-style:none; margin:0; padding:0; ">
        <li style="margin:0 0 0; padding:0 0 0; border:0; float:left; margin-left:20px;"><a href="https://twitter.com/" class="fab fa-twitter" style="color:skyblue">
          <span class="label" style="font-family:'Acme', sans-serif;">Twitter</span></a></li>
        <li style="margin:0 0 0; padding:0 0 0; border:0; float:left; margin-left:20px;"><a href="https://www.facebook.com/" class="fab fa-facebook" style="color:royalblue">
          <span class="label" style="font-family:'Acme', sans-serif;">Facebook</span></a></li>
        <li style="margin:0 0 0; padding:0 0 0; border:0; float:left; margin-left:20px;"><a href="https://www.instagram.com/" class="fab fa-instagram" style="color:rebeccapurple">
          <span class="label" style="font-family:'Acme', sans-serif; font-weight:bold;">Instagram</span></a></li>
        <li style="margin:0 0 0; padding:0 0 0; border:0; float:left; margin-left:20px;"><a href="https://mail.naver.com/" class="fas fa-envelope" style="color:orchid">
          <span class="label" style="font-family:'Acme', sans-serif;">Email</span></a></li>
        <li style="margin:0 0 0; padding:0 0 0; border:0; float:left; margin-left:20px; margin-right:20px;"><a><span class="copyright; text-align:center;" style="color:white; font-family:'Acme', sans-serif;">&copy; HIHIGH</span></a></li>
      </ul>
    </div>
  </footer>

</body>
</html>